### ISSUE TITLE
Error while running Named Entity Recognition

### ISSUE THREAD

**Issue by Sachit1137** [allenai/scibert#97]
I tried using SciBERT for NER using the following command-

from transformers import *

tokenizer = AutoTokenizer.from_pretrained('allenai/scibert_scivocab_uncased')
model = AutoModel.from_pretrained('allenai/scibert_scivocab_uncased')

nlp = pipeline('ner',model = model,tokenizer=tokenizer)
nlp('Clinical features of culture-proven Mycoplasma pneumoniae infections at King Abdulaziz University Hospital, Jeddah, Saudi Arabia')

While running it on a sample sentence, I get the following error-
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python3.6/site-packages/transformers/pipelines.py", line 927, in __call__
    for idx, label_idx in enumerate(labels_idx)
  File "/python3.6/site-packages/transformers/pipelines.py", line 928, in <listcomp>
    if self.model.config.id2label[label_idx] not in self.ignore_labels
KeyError: 422

**Comment by elkotito** [comment]
```
from transformers import BertTokenizer, BertForTokenClassification
tokenizer = BertTokenizer.from_pretrained('allenai/scibert_scivocab_uncased')
model = BertForTokenClassification.from_pretrained('allenai/scibert_scivocab_uncased')
nlp = pipeline('ner', model=model, tokenizer=tokenizer)

text = 'Clinical features of culture-proven Mycoplasma pneumoniae infections at King Abdulaziz University Hospital, Jeddah, Saudi Arabia'
print(nlp(text))
```
